/* OutTrack — extra meals (DE base) + EN translations. RU/ES/FR fall back to EN. */
const MEALS_EXTRA = [
{ cat: "protein", kcal: 380, mins: 10, name: "Rührei mit Tomaten & Feta", desc: "Fluffig, würzig, proteinreich.",
ing: ["3 Eier", "1 Tomate", "40 g Feta", "1 TL Butter", "Salz, Pfeffer"], steps: ["Tomate würfeln, in Butter anschwitzen.", "Eier verquirlt zugeben, stocken lassen.", "Feta darüberbröseln."] },
{ cat: "energie", kcal: 420, mins: 5, name: "Overnight Oats mit Apfel", desc: "Abends vorbereitet, morgens fertig.",
ing: ["50 g Haferflocken", "150 g Joghurt", "100 ml Milch", "1 Apfel", "Zimt"], steps: ["Alles außer Apfel mischen, kalt stellen.", "Morgens Apfel raspeln, Zimt darüber."] },
{ cat: "energie", kcal: 550, mins: 20, name: "Vollkorn-Pancakes", desc: "Flauschiger Wochenend-Klassiker.",
ing: ["120 g Vollkornmehl", "200 ml Milch", "1 Ei", "1 TL Backpulver", "Ahornsirup"], steps: ["Teig glatt rühren, kurz ruhen.", "Portionsweise goldbraun backen.", "Mit Sirup servieren."] },
{ cat: "protein", kcal: 350, mins: 5, name: "Quark mit Honig & Nüssen", desc: "40 g Protein, null Aufwand.",
ing: ["250 g Magerquark", "1 EL Honig", "20 g Nüsse", "Beeren nach Wahl"], steps: ["Quark cremig rühren.", "Honig, Nüsse, Beeren darauf."] },
{ cat: "energie", kcal: 480, mins: 10, name: "Avocado-Toast deluxe", desc: "Knusprig, cremig, sättigend.",
ing: ["2 Scheiben Sauerteigbrot", "1 Avocado", "Cherrytomaten", "1 EL Pinienkerne", "Zitrone, Salz"], steps: ["Brot toasten.", "Avocado zerdrücken, mit Zitrone und Salz würzen.", "Tomaten und Pinienkerne darauf."] },
{ cat: "energie", kcal: 460, mins: 5, name: "Müsli mit Joghurt & Banane", desc: "Der ehrliche Standard.",
ing: ["60 g Müsli", "200 g Joghurt", "1 Banane", "1 TL Leinsamen"], steps: ["Joghurt in Schale geben.", "Müsli, Banane, Leinsamen darauf."] },
{ cat: "protein", kcal: 420, mins: 20, name: "Shakshuka", desc: "Eier in würziger Tomatenpaprika-Sauce.",
ing: ["3 Eier", "400 g Tomaten (Dose)", "1 Paprika", "1 Zwiebel", "Kreuzkümmel, Paprika, Öl"], steps: ["Zwiebel und Paprika anschwitzen.", "Tomaten und Gewürze zugeben, 10 Minuten köcheln.", "Eier hineinschlagen, stocken lassen."] },
{ cat: "energie", kcal: 470, mins: 8, name: "Porridge mit Erdnussbutter", desc: "Cremig-nussig, hält ewig satt.",
ing: ["50 g Haferflocken", "250 ml Milch", "1 EL Erdnussbutter", "1 Banane"], steps: ["Porridge kochen.", "Erdnussbutter unterrühren.", "Banane darauf."] },
{ cat: "protein", kcal: 400, mins: 10, name: "Käse-Omelett mit Schnittlauch", desc: "Französisch einfach.",
ing: ["3 Eier", "40 g geriebener Käse", "Schnittlauch", "1 TL Butter"], steps: ["Eier verquirlen, in Butter stocken lassen.", "Käse und Schnittlauch darauf, klappen."] },
{ cat: "light", kcal: 300, mins: 5, name: "Chia-Pudding mit Mango", desc: "Leicht, exotisch, vorbereitbar.",
ing: ["3 EL Chiasamen", "200 ml Kokosmilch", "1/2 Mango", "Limette"], steps: ["Chia mit Kokosmilch verrühren, 2 Stunden kühlen.", "Mango würfeln, darauf, Limette darüber."] },
{ cat: "energie", kcal: 520, mins: 15, name: "French Toast Vollkorn", desc: "Süß, goldbraun, schnell.",
ing: ["4 Scheiben Vollkorntoast", "2 Eier", "100 ml Milch", "Zimt", "Ahornsirup"], steps: ["Ei, Milch, Zimt verquirlen.", "Brotscheiben tränken, goldbraun braten.", "Mit Sirup servieren."] },
{ cat: "protein", kcal: 330, mins: 5, name: "Hüttenkäse-Brot mit Kresse", desc: "Frisch und eiweißreich.",
ing: ["2 Scheiben Roggenbrot", "200 g Hüttenkäse", "Kresse", "Salz, Pfeffer"], steps: ["Brot bestreichen.", "Kresse darauf, würzen."] },
{ cat: "energie", kcal: 380, mins: 8, name: "Smoothie-Bowl Beere-Banane", desc: "Eisgekühlt löffeln.",
ing: ["1 Banane (gefroren)", "100 g Beeren (gefroren)", "100 ml Milch", "2 EL Granola"], steps: ["Alles außer Granola cremig mixen.", "In Schale, Granola darauf."] },
{ cat: "protein", kcal: 320, mins: 25, name: "Ei-Muffins mit Gemüse", desc: "Meal-Prep für die Woche.",
ing: ["6 Eier", "1 Paprika", "1 Handvoll Spinat", "50 g Feta", "Salz, Pfeffer"], steps: ["Ofen auf 180 °C.", "Alles verquirlen, in Muffinform füllen.", "20 Minuten backen."] },
{ cat: "energie", kcal: 450, mins: 12, name: "Grießbrei mit Kirschen", desc: "Kindheit in einer Schale.",
ing: ["60 g Grieß", "500 ml Milch", "1 EL Zucker", "200 g Kirschen (Glas)", "Zimt"], steps: ["Milch aufkochen, Grieß einrieseln, quellen.", "Kirschen erwärmen.", "Mit Zimt servieren."] },
{ cat: "light", kcal: 500, mins: 20, name: "Buddha Bowl mit Kichererbsen", desc: "Bunt, knackig, pflanzlich.",
ing: ["80 g Quinoa", "200 g Kichererbsen (Dose)", "1 Karotte", "1/2 Rotkohl", "Tahin-Zitrone-Dressing"], steps: ["Quinoa kochen.", "Gemüse raspeln, Kichererbsen rösten.", "Anrichten, Dressing darüber."] },
{ cat: "protein", kcal: 600, mins: 25, name: "Teriyaki-Hähnchen mit Reis", desc: "Süß-salzig, besser als Lieferdienst.",
ing: ["150 g Hähnchenbrust", "80 g Reis", "3 EL Teriyakisauce", "1 Frühlingszwiebel", "Sesam"], steps: ["Reis kochen.", "Hähnchen braten, mit Sauce glasieren.", "Mit Zwiebel und Sesam servieren."] },
{ cat: "protein", kcal: 580, mins: 20, name: "Lachs-Poke-Bowl", desc: "Hawaii-Feeling ohne Flug.",
ing: ["120 g Lachs (Sushi-Qualität)", "100 g Sushi-Reis", "1/2 Gurke", "1/2 Mango", "Sojasauce, Sesam"], steps: ["Reis kochen, abkühlen.", "Lachs würfeln, kurz marinieren.", "Bowl schichten."] },
{ cat: "energie", kcal: 620, mins: 25, name: "Falafel-Bowl mit Hummus", desc: "Knusprig plus cremig.",
ing: ["6 Falafel", "80 g Bulgur", "100 g Salat", "3 EL Hummus", "Granatapfelkerne"], steps: ["Bulgur quellen lassen.", "Falafel nach Packung backen/braten.", "Bowl bauen, Hummus und Kerne darauf."] },
{ cat: "protein", kcal: 520, mins: 20, name: "Garnelen-Reispfanne", desc: "Schnell, leicht, edel.",
ing: ["150 g Garnelen", "80 g Reis", "1 Paprika", "2 Knoblauchzehen", "Sojasauce, Limette, Öl"], steps: ["Reis kochen.", "Garnelen mit Knoblauch 3 Minuten braten.", "Alles mischen, Limette darüber."] },
{ cat: "light", kcal: 480, mins: 25, name: "Curry-Reis mit Gemüse", desc: "Ein Topf, null Abwasch-Drama.",
ing: ["80 g Reis", "300 g TK-Gemüse", "200 ml Kokosmilch", "2 EL Currypaste", "Limette"], steps: ["Paste anrösten, Kokosmilch zugeben.", "Reis und Gemüse 18 Minuten garen.", "Limette darüber."] },
{ cat: "protein", kcal: 500, mins: 15, name: "Thunfisch-Poke", desc: "Frisch, schnell, proteinreich.",
ing: ["150 g Thunfisch (Sushi-Qualität)", "100 g Reis", "1/2 Avocado", "Edamame", "Sojasauce, Sesam"], steps: ["Reis kochen.", "Thunfisch würfeln, marinieren.", "Bowl schichten."] },
{ cat: "protein", kcal: 640, mins: 25, name: "Rindfleisch-Brokkoli-Reis", desc: "Asia-Klassiker aus einer Pfanne.",
ing: ["150 g Rinderstreifen", "200 g Brokkoli", "80 g Reis", "3 EL Sojasauce", "Ingwer, Knoblauch, Öl"], steps: ["Reis kochen.", "Rind scharf anbraten, herausnehmen.", "Brokkoli braten, alles mit Sauce mischen."] },
{ cat: "light", kcal: 520, mins: 30, name: "Süßkartoffel-Kichererbsen-Bowl", desc: "Ofenliebe in einer Schale.",
ing: ["1 Süßkartoffel", "200 g Kichererbsen", "80 g Quinoa", "1 TL Paprika", "Joghurt-Dip"], steps: ["Ofen 200 °C, Süßkartoffel und Kichererbsen 25 Minuten rösten.", "Quinoa kochen.", "Anrichten, Dip dazu."] },
{ cat: "energie", kcal: 550, mins: 15, name: "Egg-Fried-Rice", desc: "Resteverwertung auf Profi-Niveau.",
ing: ["250 g gekochter Reis (Vortag)", "2 Eier", "100 g Erbsen & Mais", "3 EL Sojasauce", "Frühlingszwiebeln"], steps: ["Reis in heißem Öl knusprig braten.", "Eier verrührt unterrühren, stocken.", "Gemüse und Sauce zugeben."] },
{ cat: "energie", kcal: 620, mins: 25, name: "Mango-Hähnchen-Curry", desc: "Fruchtig-scharf, Reis dazu.",
ing: ["150 g Hähnchen", "1 Mango", "200 ml Kokosmilch", "2 EL Currypaste", "80 g Reis"], steps: ["Reis kochen.", "Hähnchen braten, Paste und Kokosmilch zugeben.", "Mango 5 Minuten mitgaren."] },
{ cat: "energie", kcal: 500, mins: 15, name: "Kimchi-Reis mit Ei", desc: "Sauer-scharf, Spiegelei oben.",
ing: ["250 g gekochter Reis", "100 g Kimchi", "2 Eier", "1 EL Gochujang", "Sesamöl"], steps: ["Kimchi anbraten, Reis und Gochujang zugeben.", "Spiegeleier braten.", "Anrichten, Sesamöl darüber."] },
{ cat: "protein", kcal: 680, mins: 30, name: "Spaghetti Bolognese", desc: "Sonntags-Sauce für jeden Tag.",
ing: ["100 g Spaghetti", "150 g Rinderhack", "400 g Tomaten (Dose)", "1 Zwiebel", "Parmesan, Oregano"], steps: ["Hack krümelig braten, Zwiebel dazu.", "Tomaten zugeben, 20 Minuten köcheln.", "Mit Pasta und Parmesan servieren."] },
{ cat: "light", kcal: 520, mins: 20, name: "Pasta al Pomodoro", desc: "Weniger ist mehr.",
ing: ["100 g Spaghetti", "400 g Tomaten (Dose)", "2 Knoblauchzehen", "Basilikum", "Parmesan, Olivenöl"], steps: ["Knoblauch anschwitzen, Tomaten 15 Minuten einkochen.", "Pasta al dente kochen.", "Mischen, Basilikum und Parmesan."] },
{ cat: "protein", kcal: 700, mins: 25, name: "Lachs-Sahne-Tagliatelle", desc: "Cremig, edel, schnell.",
ing: ["100 g Tagliatelle", "120 g Lachs", "150 ml Sahne", "1 Zitrone", "Dill"], steps: ["Pasta kochen.", "Lachs würfeln, kurz braten, Sahne zugeben.", "Zitrone und Dill, mischen."] },
{ cat: "protein", kcal: 720, mins: 25, name: "Hähnchen-Alfredo", desc: "Comfort Food deluxe.",
ing: ["100 g Fettuccine", "150 g Hähnchen", "150 ml Sahne", "40 g Parmesan", "Knoblauch, Butter"], steps: ["Hähnchen braten, in Streifen.", "Sahne-Parmesan-Sauce einkochen.", "Alles mischen."] },
{ cat: "energie", kcal: 600, mins: 45, name: "Veggie-Lasagne", desc: "Schicht für Schicht Glück.",
ing: ["6 Lasagneplatten", "400 g Tomaten", "1 Zucchini", "250 g Ricotta", "100 g Käse"], steps: ["Ofen 180 °C, Gemüse-Tomatensauce kochen.", "Schichten: Platten, Sauce, Ricotta.", "35 Minuten backen."] },
{ cat: "light", kcal: 500, mins: 20, name: "Penne Arrabbiata", desc: "Feuer unterm Montag.",
ing: ["100 g Penne", "400 g Tomaten", "1 Chilischote", "2 Knoblauchzehen", "Petersilie"], steps: ["Chili und Knoblauch anschwitzen.", "Tomaten 15 Minuten einkochen.", "Mit Pasta mischen."] },
{ cat: "protein", kcal: 580, mins: 20, name: "Thunfisch-Tomaten-Pasta", desc: "Dose auf, glücklich.",
ing: ["100 g Pasta", "1 Dose Thunfisch", "400 g Tomaten", "1 Zwiebel", "Kapern (optional)"], steps: ["Zwiebel anschwitzen, Tomaten einkochen.", "Thunfisch unterheben.", "Mit Pasta servieren."] },
{ cat: "energie", kcal: 560, mins: 20, name: "Spinat-Ricotta-Pasta", desc: "Grün und cremig.",
ing: ["100 g Pasta", "200 g Spinat", "150 g Ricotta", "40 g Parmesan", "Muskat, Knoblauch"], steps: ["Spinat zusammenfallen lassen.", "Ricotta und Parmesan einrühren.", "Mit Pasta mischen."] },
{ cat: "protein", kcal: 620, mins: 20, name: "Carbonara light mit Erbsen", desc: "Ohne Sahne, mit Crunch.",
ing: ["100 g Spaghetti", "50 g Schinkenwürfel", "2 Eigelb", "50 g Erbsen", "Parmesan, Pfeffer"], steps: ["Pasta kochen, Erbsen mitgaren.", "Schinken knusprig braten.", "Eigelb-Parmesan unterrühren (nicht mehr kochen)."] },
{ cat: "protein", kcal: 600, mins: 20, name: "Garnelen-Knoblauch-Linguine", desc: "Italien trifft Meer.",
ing: ["100 g Linguine", "150 g Garnelen", "3 Knoblauchzehen", "Chili", "Petersilie, Olivenöl"], steps: ["Garnelen mit Knoblauch 3 Minuten braten.", "Pasta dazugeben, schwenken.", "Petersilie darüber."] },
{ cat: "light", kcal: 450, mins: 25, name: "Zucchini-Bolognese", desc: "Leicht, aber mit Biss.",
ing: ["150 g Rinderhack", "2 Zucchini", "400 g Tomaten", "1 Zwiebel", "Parmesan"], steps: ["Zucchini in Spaghetti schneiden, kurz braten.", "Bolognese wie klassisch kochen.", "Statt Pasta servieren."] },
{ cat: "energie", kcal: 700, mins: 30, name: "Käse-Spätzle", desc: "Almhütte für daheim.",
ing: ["250 g Spätzle", "150 g Bergkäse", "2 Zwiebeln", "Butter", "Schnittlauch"], steps: ["Spätzle kochen.", "Zwiebeln in Butter braun rösten.", "Mit Käse schichten, überbacken."] },
{ cat: "protein", kcal: 520, mins: 30, name: "Kabeljau mit Kartoffeln & Spinat", desc: "Nordisch, sauber, gut.",
ing: ["150 g Kabeljau", "300 g Kartoffeln", "200 g Spinat", "1 Zitrone", "Butter"], steps: ["Kartoffeln 20 Minuten kochen.", "Fisch 8 Minuten dünsten.", "Spinat schwenken, anrichten."] },
{ cat: "protein", kcal: 480, mins: 25, name: "Forelle mit Mandeln", desc: "Klassiker vom Blech.",
ing: ["1 Forelle (küchenfertig)", "30 g Mandelblättchen", "300 g Kartoffeln", "Zitrone", "Butter"], steps: ["Kartoffeln kochen.", "Forelle in Butter je Seite 4 Minuten braten.", "Mandeln rösten, darüber."] },
{ cat: "protein", kcal: 550, mins: 25, name: "Ofenlachs Honig-Senf", desc: "Glasur trifft Saftigkeit.",
ing: ["150 g Lachs", "1 EL Honig", "1 EL Senf", "300 g Brokkoli", "80 g Reis"], steps: ["Ofen 200 °C.", "Lachs glasieren, 12 Minuten backen.", "Mit Reis und Brokkoli servieren."] },
{ cat: "protein", kcal: 450, mins: 15, name: "Thunfischsteak mit Sesam", desc: "Innen glasig, außen Crunch.",
ing: ["180 g Thunfischsteak", "2 EL Sesam", "Sojasauce", "1 Limette", "Salatbeilage"], steps: ["Steak in Sesam wenden.", "Je Seite 1 Minute scharf braten.", "Mit Sojasauce und Limette."] },
{ cat: "energie", kcal: 580, mins: 25, name: "Fisch-Tacos", desc: "Straßenküche zum Selberbauen.",
ing: ["4 Tortillas", "200 g Seelachs", "100 g Rotkohl", "Limette", "Joghurt-Sauce"], steps: ["Fisch panieren oder würzen, braten.", "Kohl hobeln, Sauce rühren.", "Tacos belegen."] },
{ cat: "protein", kcal: 500, mins: 25, name: "Seelachs mit Erbsenpüree", desc: "Kantine, aber in gut.",
ing: ["150 g Seelachs", "300 g Erbsen (TK)", "300 g Kartoffeln", "Minze", "Butter"], steps: ["Kartoffeln und Erbsen kochen.", "Zu Püree stampfen, Minze dazu.", "Fisch braten, anrichten."] },
{ cat: "protein", kcal: 560, mins: 20, name: "Garnelen-Curry Kokos", desc: "Exotisch in 20 Minuten.",
ing: ["150 g Garnelen", "200 ml Kokosmilch", "2 EL rote Currypaste", "1 Paprika", "80 g Reis"], steps: ["Reis kochen.", "Paste anrösten, Kokosmilch zugeben.", "Garnelen und Paprika 5 Minuten garen."] },
{ cat: "energie", kcal: 650, mins: 30, name: "Backfisch mit Kartoffelsalat", desc: "Frittenbude-Feeling.",
ing: ["150 g Seelachsfilet", "Paniermehl & Ei", "400 g Kartoffeln", "Essig, Öl, Gurke", "Remoulade"], steps: ["Kartoffelsalat anmachen, ziehen lassen.", "Fisch panieren, goldbraun backen.", "Mit Remoulade servieren."] },
{ cat: "protein", kcal: 480, mins: 30, name: "Hähnchenbrust mit Ofengemüse", desc: "Blech rauf, Füße hoch.",
ing: ["150 g Hähnchenbrust", "400 g Ofengemüse-Mix", "2 EL Olivenöl", "Rosmarin", "Salz, Pfeffer"], steps: ["Ofen 200 °C.", "Alles aufs Blech, 25 Minuten rösten.", "Aufschneiden, servieren."] },
{ cat: "protein", kcal: 620, mins: 30, name: "Rindersteak mit Süßkartoffel", desc: "Sonntag, aber dienstags.",
ing: ["180 g Rindersteak", "1 Süßkartoffel", "100 g Bohnen", "Butter", "Salz, Pfeffer"], steps: ["Süßkartoffel 25 Minuten backen.", "Steak je Seite 2–3 Minuten braten, ruhen.", "Bohnen dämpfen, anrichten."] },
{ cat: "protein", kcal: 520, mins: 20, name: "Puten-Geschnetzeltes", desc: "Sahne, Champignons, fertig.",
ing: ["150 g Putenstreifen", "200 g Champignons", "150 ml Sahne", "1 Zwiebel", "80 g Reis"], steps: ["Reis kochen.", "Pute anbraten, Champignons dazu.", "Sahne einkochen, würzen."] },
{ cat: "protein", kcal: 600, mins: 30, name: "Hackbällchen in Tomatensauce", desc: "Klein, rund, glücklich.",
ing: ["200 g Rinderhack", "400 g Tomaten", "1 Ei", "Paniermehl", "80 g Reis"], steps: ["Hack mit Ei und Paniermehl formen.", "Bällchen braten.", "In Tomatensauce 15 Minuten schmoren."] },
{ cat: "protein", kcal: 580, mins: 25, name: "Hähnchen-Curry Madras", desc: "Feuer mit Kokos.",
ing: ["150 g Hähnchen", "200 ml Kokosmilch", "2 EL Madraspaste", "1 Zwiebel", "80 g Reis"], steps: ["Reis kochen.", "Hähnchen braten, Paste und Milch zugeben.", "15 Minuten köcheln."] },
{ cat: "protein", kcal: 550, mins: 35, name: "Schweinefilet mit Apfel-Rotkohl", desc: "Festtag ohne Anlass.",
ing: ["180 g Schweinefilet", "300 g Rotkohl (Glas/Dose)", "1 Apfel", "Senf", "Kartoffelbeilage"], steps: ["Filet anbraten, bei 160 °C 15 Minuten garen.", "Rotkohl mit Apfel erwärmen.", "Aufschneiden, mit Senf servieren."] },
{ cat: "protein", kcal: 650, mins: 60, name: "Rinder-Gulasch", desc: "Geduld wird belohnt.",
ing: ["200 g Rindergulasch", "2 Zwiebeln", "2 EL Paprikapulver", "500 ml Brühe", "Kartoffeln"], steps: ["Fleisch und Zwiebeln anrösten.", "Paprika dazu, mit Brühe ablöschen.", "60 Minuten schmoren."] },
{ cat: "protein", kcal: 520, mins: 25, name: "Chicken Nuggets selbstgemacht", desc: "Knusprig ohne Tüte.",
ing: ["150 g Hähnchenbrust", "Paniermehl & Ei & Mehl", "Paprikapulver", "Dip nach Wahl", "Salat"], steps: ["Hähnchen in Stücke, panieren.", "Im Ofen 20 Minuten backen.", "Mit Dip servieren."] },
{ cat: "protein", kcal: 600, mins: 20, name: "Puten-Burger", desc: "Leichter als Rind, genauso gut.",
ing: ["150 g Putenhack", "1 Burgerbrötchen", "Salat, Tomate", "Joghurt-Senf-Sauce", "Käse (optional)"], steps: ["Patty formen, würzen, braten.", "Brötchen toasten.", "Belegen, Sauce darauf."] },
{ cat: "protein", kcal: 450, mins: 25, name: "Hähnchenspieße mit Paprika", desc: "Vom Grill oder aus der Pfanne.",
ing: ["150 g Hähnchenbrust", "1 Paprika", "1 Zucchini", "Marinade: Öl, Paprika, Knoblauch", "Fladenbrot"], steps: ["Fleisch marinieren, aufspießen.", "Rundum 12 Minuten garen.", "Mit Brot servieren."] },
{ cat: "protein", kcal: 620, mins: 25, name: "Cevapcici mit Fladenbrot", desc: "Balkan-Abend daheim.",
ing: ["200 g Rinderhack", "1 Zwiebel", "Ajvar", "Fladenbrot", "Kajmak oder Joghurt"], steps: ["Hack würzen, Röllchen formen.", "Rundum braten.", "Mit Brot, Ajvar und Dip."] },
{ cat: "protein", kcal: 540, mins: 20, name: "Rindstreifen Asia", desc: "Wok-Hitze in 20 Minuten.",
ing: ["150 g Rinderstreifen", "200 g Wokgemüse", "3 EL Sojasauce", "Ingwer, Knoblauch", "80 g Reis"], steps: ["Reis kochen.", "Rind scharf anbraten.", "Gemüse dazu, mit Sauce ablöschen."] },
{ cat: "light", kcal: 480, mins: 25, name: "Kichererbsen-Curry", desc: "Cremig, vegan, günstig.",
ing: ["240 g Kichererbsen (Dose)", "200 ml Kokosmilch", "2 EL Currypaste", "200 g Spinat", "80 g Reis"], steps: ["Reis kochen.", "Paste anrösten, Milch und Kichererbsen 10 Minuten köcheln.", "Spinat unterheben."] },
{ cat: "light", kcal: 500, mins: 25, name: "Linsen-Bolognese", desc: "Fleischlos, aber herzhaft.",
ing: ["100 g rote Linsen", "100 g Pasta", "400 g Tomaten", "1 Karotte", "Parmesan (optional)"], steps: ["Linsen mit Tomaten 20 Minuten kochen.", "Pasta kochen.", "Mischen, servieren."] },
{ cat: "light", kcal: 470, mins: 20, name: "Gemüse-Curry Kokos", desc: "Reste retten, Geschmack gewinnen.",
ing: ["400 g Gemüse nach Wahl", "200 ml Kokosmilch", "2 EL Currypaste", "80 g Reis", "Limette"], steps: ["Reis kochen.", "Gemüse in Curry-Kokos 12 Minuten garen.", "Limette darüber."] },
{ cat: "light", kcal: 420, mins: 30, name: "Ofengemüse mit Feta", desc: "Ein Blech, null Stress.",
ing: ["500 g Gemüse-Mix", "100 g Feta", "2 EL Olivenöl", "Thymian", "Baguette"], steps: ["Ofen 200 °C, Gemüse 25 Minuten rösten.", "Feta die letzten 5 Minuten dazu.", "Mit Baguette servieren."] },
{ cat: "light", kcal: 450, mins: 25, name: "Zucchini-Puffer mit Dip", desc: "Knusprig aus der Pfanne.",
ing: ["2 Zucchini", "1 Ei", "3 EL Mehl", "Joghurt-Dip", "Salz"], steps: ["Zucchini raspeln, salzen, ausdrücken.", "Mit Ei und Mehl mischen, Puffer braten.", "Mit Dip servieren."] },
{ cat: "light", kcal: 430, mins: 25, name: "Blumenkohl-Curry", desc: "Sanft-würzig, sehr sättigend.",
ing: ["1/2 Blumenkohl", "200 ml Kokosmilch", "2 EL Currypaste", "80 g Reis", "Koriander"], steps: ["Reis kochen.", "Blumenkohl in Curry-Kokos 15 Minuten garen.", "Koriander darüber."] },
{ cat: "light", kcal: 480, mins: 35, name: "Ratatouille mit Baguette", desc: "Südfrankreich zum Löffeln.",
ing: ["1 Zucchini", "1 Aubergine", "1 Paprika", "400 g Tomaten", "Baguette, Kräuter"], steps: ["Gemüse würfeln, schichtweise schmoren.", "30 Minuten einköcheln.", "Mit Baguette servieren."] },
{ cat: "energie", kcal: 580, mins: 35, name: "Pilz-Risotto", desc: "Rühren lohnt sich.",
ing: ["80 g Risottoreis", "250 g Champignons", "500 ml Brühe", "40 g Parmesan", "1 Schalotte, Butter"], steps: ["Schalotte und Reis glasig dünsten.", "Brühe portionsweise zugeben, 20 Minuten rühren.", "Pilze und Parmesan unterheben."] },
{ cat: "light", kcal: 520, mins: 35, name: "Kürbis-Risotto", desc: "Herbst in einer Schale.",
ing: ["80 g Risottoreis", "300 g Hokkaido", "500 ml Brühe", "40 g Parmesan", "Salbei"], steps: ["Kürbis würfeln, anrösten.", "Wie Risotto garen, Kürbis mitgaren.", "Parmesan und Salbei dazu."] },
{ cat: "light", kcal: 440, mins: 25, name: "Spinat-Linsen-Dal", desc: "Indisches Soulfood.",
ing: ["120 g rote Linsen", "200 g Spinat", "400 ml Kokosmilch", "Curry, Kreuzkümmel", "80 g Reis"], steps: ["Reis kochen.", "Linsen in Kokosmilch 15 Minuten garen.", "Gewürze und Spinat dazu."] },
{ cat: "light", kcal: 500, mins: 35, name: "Auberginen-Parmesan", desc: "Italien zum Auflaufen.",
ing: ["1 Aubergine", "400 g Tomaten", "100 g Mozzarella", "Parmesan", "Basilikum"], steps: ["Aubergine in Scheiben, salzen, braten.", "Mit Sauce und Käse schichten.", "25 Minuten überbacken."] },
{ cat: "light", kcal: 490, mins: 25, name: "Mais-Chili sin carne", desc: "Rauchig, deftig, vegan.",
ing: ["200 g Mais", "240 g Kidneybohnen", "400 g Tomaten", "Chili, Kreuzkümmel", "Reis oder Brot"], steps: ["Alles in einen Topf.", "20 Minuten köcheln.", "Mit Reis oder Brot servieren."] },
{ cat: "protein", kcal: 480, mins: 20, name: "Caesar Salad mit Hähnchen", desc: "Knackig mit Kult-Dressing.",
ing: ["150 g Hähnchenbrust", "150 g Römersalat", "30 g Parmesan", "Croutons", "Caesar-Dressing"], steps: ["Hähnchen braten, aufschneiden.", "Salat waschen, mischen.", "Dressing, Parmesan, Croutons."] },
{ cat: "light", kcal: 380, mins: 10, name: "Griechischer Bauernsalat", desc: "Urlaub in 10 Minuten.",
ing: ["2 Tomaten", "1/2 Gurke", "1/2 rote Zwiebel", "100 g Feta", "Oliven, Oregano, Öl"], steps: ["Alles grob schneiden.", "Feta darüber, Öl und Oregano."] },
{ cat: "light", kcal: 420, mins: 15, name: "Couscous-Salat", desc: "Fluffig-frisch, meal-prep-tauglich.",
ing: ["80 g Couscous", "1 Paprika", "Cherrytomaten", "Minze, Petersilie", "Zitrone, Öl"], steps: ["Couscous mit heißem Wasser quellen.", "Gemüse und Kräuter untermischen.", "Zitronig anmachen."] },
{ cat: "light", kcal: 450, mins: 20, name: "Quinoa-Salat mit Avocado", desc: "Sattmacher mit guten Fetten.",
ing: ["80 g Quinoa", "1 Avocado", "100 g Cherrytomaten", "Limette", "Koriander"], steps: ["Quinoa kochen, abkühlen.", "Alles würfeln und mischen.", "Limette darüber."] },
{ cat: "energie", kcal: 520, mins: 20, name: "Nudelsalat mediterran", desc: "Grillbeilagen-König.",
ing: ["100 g Fusilli", "100 g getrocknete Tomaten", "50 g Oliven", "50 g Feta", "Basilikum, Öl"], steps: ["Nudeln kochen, abkühlen.", "Alles mischen.", "Durchziehen lassen."] },
{ cat: "protein", kcal: 430, mins: 15, name: "Linsen-Salat", desc: "Eiweiß aus der Dose.",
ing: ["240 g Belugalinsen (Dose/Glas)", "1 Paprika", "1 Apfel", "Walnüsse", "Senf-Honig-Dressing"], steps: ["Linsen abspülen.", "Paprika und Apfel würfeln.", "Mit Dressing und Nüssen mischen."] },
{ cat: "light", kcal: 350, mins: 15, name: "Eier-Salat leicht", desc: "Mit Joghurt statt Mayo.",
ing: ["3 Eier", "150 g Joghurt", "1 EL Senf", "Schnittlauch", "Vollkornbrot"], steps: ["Eier 8 Minuten kochen, würfeln.", "Mit Joghurt und Senf mischen.", "Schnittlauch darüber, Brot dazu."] },
{ cat: "light", kcal: 380, mins: 10, name: "Feldsalat mit Ziegenkäse", desc: "Nussig, cremig, edel.",
ing: ["100 g Feldsalat", "80 g Ziegenkäse", "Walnüsse", "1 Birne", "Honig-Senf-Dressing"], steps: ["Salat waschen.", "Birne aufschneiden, Käse zerbröseln.", "Anmachen, Nüsse darüber."] },
{ cat: "light", kcal: 360, mins: 15, name: "Tabouleh", desc: "Petersilien-Power aus Beirut.",
ing: ["60 g Bulgur", "1 Bund Petersilie", "2 Tomaten", "Minze", "Zitrone, Öl"], steps: ["Bulgur quellen lassen.", "Kräuter und Tomaten fein schneiden.", "Alles mischen, zitronig würzen."] },
{ cat: "light", kcal: 400, mins: 30, name: "Kartoffelsalat schwäbisch", desc: "Ohne Mayo, mit Brühe.",
ing: ["500 g Kartoffeln", "1 Zwiebel", "150 ml Brühe", "Essig, Öl, Senf", "Schnittlauch"], steps: ["Kartoffeln kochen, pellen, hobeln.", "Heiße Brühe-Marinade darüber.", "Ziehen lassen, Schnittlauch."] },
{ cat: "light", kcal: 320, mins: 25, name: "Kürbissuppe", desc: "Samtig-orange Herbstliebe.",
ing: ["500 g Hokkaido", "1 Zwiebel", "500 ml Brühe", "100 ml Sahne", "Ingwer, Curry"], steps: ["Kürbis und Zwiebel anschwitzen.", "Mit Brühe 15 Minuten garen.", "Pürieren, Sahne dazu."] },
{ cat: "light", kcal: 300, mins: 20, name: "Tomatensuppe mit Basilikum", desc: "Einfach, ehrlich, gut.",
ing: ["800 g Tomaten (Dose)", "1 Zwiebel", "500 ml Brühe", "Basilikum", "Sahnehäubchen"], steps: ["Zwiebel anschwitzen, Tomaten 15 Minuten köcheln.", "Pürieren.", "Basilikum und Sahne darauf."] },
{ cat: "protein", kcal: 380, mins: 45, name: "Hühnersuppe klassisch", desc: "Omas Medizin.",
ing: ["200 g Hähnchenbrust", "2 Karotten", "1 Stange Lauch", "100 g Suppennudeln", "1 l Brühe"], steps: ["Hähnchen in Brühe 20 Minuten garen.", "Gemüse zugeben, 15 Minuten köcheln.", "Nudeln mitgaren, Fleisch zerpflücken."] },
{ cat: "light", kcal: 350, mins: 30, name: "Minestrone", desc: "Italienischer Gemüsetopf.",
ing: ["300 g Gemüse-Mix", "100 g weiße Bohnen (Dose)", "50 g kleine Pasta", "700 ml Brühe", "Parmesan"], steps: ["Gemüse anschwitzen.", "Brühe zugeben, 20 Minuten köcheln.", "Bohnen und Pasta mitgaren."] },
{ cat: "light", kcal: 400, mins: 30, name: "Kartoffelsuppe", desc: "Deftig-cremig zum Löffeln.",
ing: ["500 g Kartoffeln", "1 Lauch", "700 ml Brühe", "100 ml Sahne", "Majoran, Würstchen (optional)"], steps: ["Alles 20 Minuten garen.", "Pürieren, Sahne dazu.", "Mit Majoran abschmecken."] },
{ cat: "light", kcal: 330, mins: 20, name: "Brokkoli-Creme-Suppe", desc: "Grün, samtig, schnell.",
ing: ["500 g Brokkoli", "1 Kartoffel", "500 ml Brühe", "100 ml Sahne", "Muskat"], steps: ["Alles 15 Minuten garen.", "Pürieren.", "Sahne und Muskat dazu."] },
{ cat: "protein", kcal: 420, mins: 30, name: "Pho light mit Hähnchen", desc: "Vietnams Seelenwärmer.",
ing: ["100 g Reisnudeln", "150 g Hähnchenbrust", "1 l Brühe", "Ingwer, Sternanis", "Limetten, Kräuter, Sojasauce"], steps: ["Brühe mit Gewürzen 15 Minuten köcheln.", "Hähnchen darin garen, aufschneiden.", "Nudeln überbrühen, alles anrichten."] },
{ cat: "light", kcal: 380, mins: 30, name: "Erbsensuppe", desc: "Deftig ohne Speck geht auch.",
ing: ["400 g Schälerbsen", "2 Karotten", "1 Zwiebel", "1 l Brühe", "Majoran"], steps: ["Erbsen 1 Stunde einweichen (oder TK).", "Alles 30 Minuten köcheln.", "Teilweise pürieren, würzen."] },
{ cat: "light", kcal: 300, mins: 10, name: "Hummus mit Gemüsesticks", desc: "Dippen erlaubt.",
ing: ["240 g Kichererbsen (Dose)", "2 EL Tahin", "1 Zitrone", "Knoblauch, Kreuzkümmel", "Gemüsesticks"], steps: ["Alles außer Sticks cremig mixen.", "Mit Öl beträufeln.", "Sticks dazu."] },
{ cat: "energie", kcal: 450, mins: 10, name: "Guacamole mit Tortillachips", desc: "Mexiko in 10 Minuten.",
ing: ["2 Avocados", "1 Tomate", "1 Limette", "Koriander, Chili", "Tortillachips"], steps: ["Avocados zerdrücken.", "Tomate, Limette, Gewürze unterrühren.", "Mit Chips servieren."] },
{ cat: "energie", kcal: 350, mins: 15, name: "Protein-Balls Dattel-Kakao", desc: "Energiekugeln ohne Backen.",
ing: ["150 g Datteln", "100 g Haferflocken", "2 EL Kakao", "2 EL Erdnussbutter", "Kokosraspeln"], steps: ["Alles mixen.", "Kugeln formen.", "In Kokos wälzen, kühlen."] },
{ cat: "light", kcal: 280, mins: 30, name: "Geröstete Kichererbsen", desc: "Chips-Alternative aus dem Ofen.",
ing: ["240 g Kichererbsen (Dose)", "1 EL Olivenöl", "Paprikapulver", "Salz"], steps: ["Trocknen, mit Öl und Gewürzen mischen.", "Bei 200 °C 25 Minuten rösten."] },
{ cat: "energie", kcal: 550, mins: 15, name: "Ofen-Nachos", desc: "Filmabend-Upgrade.",
ing: ["150 g Tortillachips", "100 g Käse", "100 g Bohnen", "Jalapeños", "Salsa, Joghurt"], steps: ["Chips schichten, belegen.", "10 Minuten überbacken.", "Salsa und Joghurt dazu."] },
{ cat: "light", kcal: 320, mins: 10, name: "Bruschetta", desc: "Sommer auf Brot.",
ing: ["4 Scheiben Ciabatta", "3 Tomaten", "1 Knoblauchzehe", "Basilikum", "Olivenöl"], steps: ["Brot toasten, mit Knoblauch einreiben.", "Tomaten würfeln, würzen.", "Belegen, Öl darüber."] },
{ cat: "light", kcal: 350, mins: 10, name: "Tzatziki mit Fladenbrot", desc: "Griechenland zum Dippen.",
ing: ["250 g Joghurt", "1/2 Gurke", "1 Knoblauchzehe", "Dill", "Fladenbrot, Olivenöl"], steps: ["Gurke raspeln, ausdrücken.", "Mit Joghurt und Knoblauch mischen.", "Öl darüber, Brot dazu."] },
{ cat: "protein", kcal: 250, mins: 8, name: "Edamame mit Meersalz", desc: "Sushi-Bar-Snack daheim.",
ing: ["300 g Edamame (TK)", "Meersalz", "Chiliflocken (optional)"], steps: ["5 Minuten kochen oder dämpfen.", "Salzen, warm snacken."] },
{ cat: "energie", kcal: 400, mins: 5, name: "Nuss-Mix selbstgemacht", desc: "Trail-Mix ohne Zuckerfalle.",
ing: ["50 g Mandeln", "50 g Walnüsse", "30 g dunkle Schokodrops", "30 g Rosinen"], steps: ["Alles mischen.", "Portionieren."] },
{ cat: "energie", kcal: 300, mins: 5, name: "Apfelspalten mit Mandelmus", desc: "Knackig-cremiger Snack.",
ing: ["1 Apfel", "2 EL Mandelmus", "Zimt"], steps: ["Apfel in Spalten schneiden.", "Mandelmus dazu, Zimt darüber."] },
{ cat: "light", kcal: 260, mins: 5, name: "Reiswaffeln mit Hüttenkäse", desc: "Leicht und schnell.",
ing: ["2 Reiswaffeln", "100 g Hüttenkäse", "Kresse oder Tomate", "Salz, Pfeffer"], steps: ["Waffeln bestreichen.", "Belegen, würzen."] },
{ cat: "protein", kcal: 320, mins: 5, name: "Bananen-Proteinshake", desc: "Post-Workout in 5 Minuten.",
ing: ["1 Banane", "250 ml Milch", "1 Portion Proteinpulver", "Eiswürfel"], steps: ["Alles mixen.", "Eiskalt trinken."] },
{ cat: "energie", kcal: 600, mins: 20, name: "Falafel-Wrap", desc: "Streetfood zum Einrollen.",
ing: ["1 Tortilla", "5 Falafel", "Salat, Tomate", "2 EL Hummus", "Joghurt-Sauce"], steps: ["Falafel erwärmen.", "Tortilla bestreichen und belegen.", "Fest aufrollen."] },
{ cat: "energie", kcal: 620, mins: 15, name: "Halloumi-Burger", desc: "Quietschend gut.",
ing: ["1 Burgerbrötchen", "120 g Halloumi", "Salat, Tomate", "Honig-Senf-Sauce", "Rote Zwiebel"], steps: ["Halloumi goldbraun braten.", "Brötchen toasten.", "Belegen, Sauce darauf."] },
{ cat: "protein", kcal: 580, mins: 15, name: "Club-Sandwich Hähnchen", desc: "Dreistöckig glücklich.",
ing: ["3 Scheiben Toast", "100 g Hähnchenbrust", "2 Scheiben Käse", "Salat, Tomate", "Mayo/Senf"], steps: ["Hähnchen braten, Toast toasten.", "Schichten, diagonal schneiden.", "Spießchen rein."] },
{ cat: "protein", kcal: 480, mins: 10, name: "Thunfisch-Sandwich", desc: "Pausenbrot-Upgrade.",
ing: ["2 Scheiben Vollkornbrot", "1 Dose Thunfisch", "1 EL Joghurt", "Gurke, Salat", "Zitrone"], steps: ["Thunfisch mit Joghurt und Zitrone mischen.", "Brot belegen.", "Zusammenklappen."] },
{ cat: "light", kcal: 500, mins: 25, name: "Linsen-Burger", desc: "Patty aus der Dose.",
ing: ["240 g Linsen (Dose)", "1 Burgerbrötchen", "Haferflocken zum Binden", "Salat, Tomate", "BBQ-Sauce"], steps: ["Linsen stampfen, Pattys formen.", "Braten oder backen.", "Belegen."] },
{ cat: "protein", kcal: 650, mins: 30, name: "Hähnchen-Döner selbstgemacht", desc: "Besser als die Bude.",
ing: ["150 g Hähnchen", "1 Fladenbrot", "Salat, Tomate, Gurke", "Joghurt-Knoblauch-Sauce", "Dönergewürz"], steps: ["Hähnchen würzen, braten, aufschneiden.", "Brot aufbacken, aufschneiden.", "Füllen, Sauce darauf."] },
{ cat: "energie", kcal: 600, mins: 15, name: "Quesadilla Käse-Bohnen", desc: "Knusprig, käsig, schnell.",
ing: ["2 Tortillas", "100 g Käse", "100 g schwarze Bohnen", "Mais", "Salsa"], steps: ["Eine Tortilla belegen.", "Zweite darauf, beidseitig knusprig braten.", "In Dreiecke schneiden."] },
{ cat: "energie", kcal: 550, mins: 10, name: "Panini Caprese", desc: "Toast mit Italien-Seele.",
ing: ["1 Ciabatta-Brötchen", "125 g Mozzarella", "2 Tomaten", "Basilikum", "Pesto"], steps: ["Brötchen mit Pesto bestreichen.", "Belegen.", "Toasten bis der Käse läuft."] },
{ cat: "protein", kcal: 520, mins: 10, name: "Lachs-Bagel", desc: "Brunch-Klassiker.",
ing: ["1 Bagel", "100 g Räucherlachs", "Frischkäse", "Rucola", "Zitrone, Dill"], steps: ["Bagel toasten, bestreichen.", "Lachs und Rucola darauf.", "Zitrone und Dill."] },
{ cat: "protein", kcal: 420, mins: 10, name: "Ei-Sandwich mit Kresse", desc: "Einfach, schnell, gut.",
ing: ["2 Scheiben Toast", "2 Eier", "Kresse", "1 EL Joghurt", "Salz, Pfeffer"], steps: ["Eier kochen, würfeln.", "Mit Joghurt mischen.", "Belegen, Kresse darauf."] },
{ cat: "protein", kcal: 400, mins: 35, name: "Quarkauflauf mit Beeren", desc: "Kuchen, der Protein kann.",
ing: ["500 g Magerquark", "2 Eier", "50 g Grieß", "200 g Beeren", "Vanille, Süße nach Wahl"], steps: ["Alles verrühren.", "Bei 180 °C 30 Minuten backen.", "Warm oder kalt servieren."] },
{ cat: "protein", kcal: 420, mins: 25, name: "Protein-Milchreis", desc: "Soulfood mit Sinn.",
ing: ["80 g Milchreis", "500 ml Milch", "1 Portion Vanille-Protein", "Zimt", "Kirschen (optional)"], steps: ["Milchreis 20 Minuten garen.", "Protein einrühren.", "Zimt darüber."] },
{ cat: "light", kcal: 320, mins: 25, name: "Gebackene Äpfel mit Quark", desc: "Winter-Dessert light.",
ing: ["2 Äpfel", "200 g Magerquark", "Zimt", "1 TL Honig", "Walnüsse"], steps: ["Äpfel aushöhlen, 20 Minuten backen.", "Quark mit Zimt und Honig verrühren.", "Füllen, Nüsse darüber."] },
{ cat: "protein", kcal: 350, mins: 10, name: "Schoko-Proteinmousse", desc: "Dessert ohne Reue.",
ing: ["250 g Magerquark", "1 EL Kakao", "1 Portion Schoko-Protein", "100 ml Milch", "Beeren"], steps: ["Alles cremig mixen.", "Kalt stellen.", "Beeren darauf."] },
{ cat: "light", kcal: 330, mins: 15, name: "Grießflammerie leicht", desc: "Wackelpudding für Erwachsene.",
ing: ["40 g Grieß", "400 ml Milch", "1 Eiweiß", "Vanille", "Fruchtsauce"], steps: ["Grießbrei kochen, abkühlen.", "Eischnee unterheben.", "Kalt stellen, Sauce dazu."] },
{ cat: "light", kcal: 280, mins: 10, name: "Joghurt-Eis Beere", desc: "Nicecream ohne Maschine.",
ing: ["200 g Beeren (gefroren)", "150 g Joghurt", "1 EL Honig"], steps: ["Alles cremig mixen.", "Sofort löffeln oder frosten."] },
{ cat: "light", kcal: 220, mins: 5, name: "Grüner Smoothie", desc: "Vitamin-Schub im Glas.",
ing: ["1 Handvoll Spinat", "1/2 Mango", "1 Banane", "200 ml Wasser", "Limette"], steps: ["Alles mixen.", "Eiskalt trinken."] },
{ cat: "light", kcal: 280, mins: 5, name: "Mango-Lassi", desc: "Indisch-cremig, leicht.",
ing: ["1 Mango", "200 g Joghurt", "100 ml Milch", "Kardamom", "Eis"], steps: ["Alles mixen.", "Mit Kardamom bestäuben."] },
{ cat: "protein", kcal: 300, mins: 5, name: "Kakao-Protein warm", desc: "Abend-Schokotraum mit Sinn.",
ing: ["250 ml Milch", "1 EL Kakao", "1 Portion Schoko-Protein"], steps: ["Milch erwärmen.", "Kakao und Protein einrühren."] }
];

const MEALS_TR_EXTRA = { en: [
{ name: "Scrambled eggs with tomato & feta", desc: "Fluffy, savory, high-protein.", ing: ["3 eggs", "1 tomato", "40 g feta", "1 tsp butter", "Salt, pepper"], steps: ["Sauté diced tomato in butter.", "Add beaten eggs, let set.", "Crumble feta on top."] },
{ name: "Overnight oats with apple", desc: "Prepped at night, ready in the morning.", ing: ["50 g oats", "150 g yogurt", "100 ml milk", "1 apple", "Cinnamon"], steps: ["Mix all but apple, chill overnight.", "Grate apple on top with cinnamon."] },
{ name: "Whole-grain pancakes", desc: "Fluffy weekend classic.", ing: ["120 g whole-grain flour", "200 ml milk", "1 egg", "1 tsp baking powder", "Maple syrup"], steps: ["Stir smooth batter, rest briefly.", "Fry golden portions.", "Serve with syrup."] },
{ name: "Quark with honey & nuts", desc: "40 g protein, zero effort.", ing: ["250 g low-fat quark", "1 tbsp honey", "20 g nuts", "Berries"], steps: ["Stir quark creamy.", "Top with honey, nuts, berries."] },
{ name: "Avocado toast deluxe", desc: "Crunchy, creamy, filling.", ing: ["2 slices sourdough", "1 avocado", "Cherry tomatoes", "1 tbsp pine nuts", "Lemon, salt"], steps: ["Toast bread.", "Mash avocado with lemon and salt.", "Top with tomatoes and pine nuts."] },
{ name: "Muesli with yogurt & banana", desc: "The honest standard.", ing: ["60 g muesli", "200 g yogurt", "1 banana", "1 tsp flaxseed"], steps: ["Yogurt into a bowl.", "Add muesli, banana, flaxseed."] },
{ name: "Shakshuka", desc: "Eggs in spicy tomato-pepper sauce.", ing: ["3 eggs", "400 g canned tomatoes", "1 bell pepper", "1 onion", "Cumin, paprika, oil"], steps: ["Sauté onion and pepper.", "Add tomatoes and spices, simmer 10 min.", "Crack in eggs, let set."] },
{ name: "Porridge with peanut butter", desc: "Creamy-nutty, keeps you full.", ing: ["50 g oats", "250 ml milk", "1 tbsp peanut butter", "1 banana"], steps: ["Cook porridge.", "Stir in peanut butter.", "Top with banana."] },
{ name: "Cheese omelette with chives", desc: "Simply French.", ing: ["3 eggs", "40 g grated cheese", "Chives", "1 tsp butter"], steps: ["Set beaten eggs in butter.", "Add cheese and chives, fold."] },
{ name: "Chia pudding with mango", desc: "Light, exotic, preppable.", ing: ["3 tbsp chia seeds", "200 ml coconut milk", "1/2 mango", "Lime"], steps: ["Stir chia with coconut milk, chill 2 hrs.", "Dice mango on top, lime over."] },
{ name: "Whole-grain French toast", desc: "Sweet, golden, fast.", ing: ["4 slices whole-grain toast", "2 eggs", "100 ml milk", "Cinnamon", "Maple syrup"], steps: ["Whisk egg, milk, cinnamon.", "Soak slices, fry golden.", "Serve with syrup."] },
{ name: "Cottage cheese bread with cress", desc: "Fresh and protein-rich.", ing: ["2 slices rye bread", "200 g cottage cheese", "Cress", "Salt, pepper"], steps: ["Spread bread.", "Top with cress, season."] },
{ name: "Berry-banana smoothie bowl", desc: "Spoon it ice-cold.", ing: ["1 frozen banana", "100 g frozen berries", "100 ml milk", "2 tbsp granola"], steps: ["Blend all but granola creamy.", "Bowl it, add granola."] },
{ name: "Veggie egg muffins", desc: "Meal prep for the week.", ing: ["6 eggs", "1 bell pepper", "1 handful spinach", "50 g feta", "Salt, pepper"], steps: ["Oven to 180 °C.", "Whisk all, fill muffin tin.", "Bake 20 min."] },
{ name: "Semolina pudding with cherries", desc: "Childhood in a bowl.", ing: ["60 g semolina", "500 ml milk", "1 tbsp sugar", "200 g cherries", "Cinnamon"], steps: ["Boil milk, whisk in semolina.", "Warm cherries.", "Serve with cinnamon."] },
{ name: "Buddha bowl with chickpeas", desc: "Colorful, crunchy, plant-based.", ing: ["80 g quinoa", "200 g chickpeas (can)", "1 carrot", "1/2 red cabbage", "Tahini-lemon dressing"], steps: ["Cook quinoa.", "Grate veg, roast chickpeas.", "Assemble, dress."] },
{ name: "Teriyaki chicken with rice", desc: "Sweet-salty, beats delivery.", ing: ["150 g chicken breast", "80 g rice", "3 tbsp teriyaki sauce", "1 spring onion", "Sesame"], steps: ["Cook rice.", "Fry chicken, glaze with sauce.", "Serve with onion and sesame."] },
{ name: "Salmon poke bowl", desc: "Hawaii vibes, no flight.", ing: ["120 g salmon (sushi-grade)", "100 g sushi rice", "1/2 cucumber", "1/2 mango", "Soy sauce, sesame"], steps: ["Cook rice, cool.", "Cube salmon, marinate briefly.", "Layer bowl."] },
{ name: "Falafel bowl with hummus", desc: "Crunchy plus creamy.", ing: ["6 falafel", "80 g bulgur", "100 g salad", "3 tbsp hummus", "Pomegranate seeds"], steps: ["Soak bulgur.", "Bake/fry falafel.", "Build bowl with hummus and seeds."] },
{ name: "Shrimp rice pan", desc: "Fast, light, classy.", ing: ["150 g shrimp", "80 g rice", "1 bell pepper", "2 garlic cloves", "Soy sauce, lime, oil"], steps: ["Cook rice.", "Fry shrimp with garlic 3 min.", "Mix all, lime over."] },
{ name: "Curry rice with veg", desc: "One pot, zero dish drama.", ing: ["80 g rice", "300 g frozen veg", "200 ml coconut milk", "2 tbsp curry paste", "Lime"], steps: ["Fry paste, add coconut milk.", "Cook rice and veg 18 min.", "Lime over."] },
{ name: "Tuna poke", desc: "Fresh, fast, protein-rich.", ing: ["150 g tuna (sushi-grade)", "100 g rice", "1/2 avocado", "Edamame", "Soy sauce, sesame"], steps: ["Cook rice.", "Cube tuna, marinate.", "Layer bowl."] },
{ name: "Beef broccoli rice", desc: "Asian classic from one pan.", ing: ["150 g beef strips", "200 g broccoli", "80 g rice", "3 tbsp soy sauce", "Ginger, garlic, oil"], steps: ["Cook rice.", "Sear beef, set aside.", "Fry broccoli, mix with sauce."] },
{ name: "Sweet potato chickpea bowl", desc: "Oven love in a bowl.", ing: ["1 sweet potato", "200 g chickpeas", "80 g quinoa", "1 tsp paprika", "Yogurt dip"], steps: ["Roast at 200 °C for 25 min.", "Cook quinoa.", "Assemble with dip."] },
{ name: "Egg fried rice", desc: "Leftovers at pro level.", ing: ["250 g cooked rice (day-old)", "2 eggs", "100 g peas & corn", "3 tbsp soy sauce", "Spring onions"], steps: ["Fry rice crispy in hot oil.", "Stir in beaten eggs.", "Add veg and sauce."] },
{ name: "Mango chicken curry", desc: "Fruity-spicy with rice.", ing: ["150 g chicken", "1 mango", "200 ml coconut milk", "2 tbsp curry paste", "80 g rice"], steps: ["Cook rice.", "Fry chicken, add paste and milk.", "Simmer mango 5 min."] },
{ name: "Kimchi rice with egg", desc: "Sour-spicy with fried egg on top.", ing: ["250 g cooked rice", "100 g kimchi", "2 eggs", "1 tbsp gochujang", "Sesame oil"], steps: ["Fry kimchi, add rice and gochujang.", "Fry eggs.", "Plate, drizzle oil."] },
{ name: "Spaghetti bolognese", desc: "Sunday sauce for every day.", ing: ["100 g spaghetti", "150 g ground beef", "400 g canned tomatoes", "1 onion", "Parmesan, oregano"], steps: ["Brown beef, add onion.", "Add tomatoes, simmer 20 min.", "Serve with pasta and parmesan."] },
{ name: "Pasta al pomodoro", desc: "Less is more.", ing: ["100 g spaghetti", "400 g canned tomatoes", "2 garlic cloves", "Basil", "Parmesan, olive oil"], steps: ["Sweat garlic, reduce tomatoes 15 min.", "Cook pasta al dente.", "Mix with basil and parmesan."] },
{ name: "Salmon cream tagliatelle", desc: "Creamy, classy, fast.", ing: ["100 g tagliatelle", "120 g salmon", "150 ml cream", "1 lemon", "Dill"], steps: ["Cook pasta.", "Cube salmon, sear, add cream.", "Lemon and dill, mix."] },
{ name: "Chicken alfredo", desc: "Comfort food deluxe.", ing: ["100 g fettuccine", "150 g chicken", "150 ml cream", "40 g parmesan", "Garlic, butter"], steps: ["Fry chicken, slice.", "Reduce cream-parmesan sauce.", "Mix all."] },
{ name: "Veggie lasagne", desc: "Layer by layer of joy.", ing: ["6 lasagne sheets", "400 g tomatoes", "1 zucchini", "250 g ricotta", "100 g cheese"], steps: ["Oven 180 °C, cook veg-tomato sauce.", "Layer sheets, sauce, ricotta.", "Bake 35 min."] },
{ name: "Penne arrabbiata", desc: "Fire under your Monday.", ing: ["100 g penne", "400 g tomatoes", "1 chili", "2 garlic cloves", "Parsley"], steps: ["Sweat chili and garlic.", "Reduce tomatoes 15 min.", "Mix with pasta."] },
{ name: "Tuna tomato pasta", desc: "Open can, be happy.", ing: ["100 g pasta", "1 can tuna", "400 g tomatoes", "1 onion", "Capers (optional)"], steps: ["Sweat onion, reduce tomatoes.", "Fold in tuna.", "Serve with pasta."] },
{ name: "Spinach ricotta pasta", desc: "Green and creamy.", ing: ["100 g pasta", "200 g spinach", "150 g ricotta", "40 g parmesan", "Nutmeg, garlic"], steps: ["Wilt spinach.", "Stir in ricotta and parmesan.", "Mix with pasta."] },
{ name: "Carbonara light with peas", desc: "No cream, with crunch.", ing: ["100 g spaghetti", "50 g ham cubes", "2 yolks", "50 g peas", "Parmesan, pepper"], steps: ["Cook pasta, add peas.", "Crisp ham.", "Stir in yolk-parmesan off heat."] },
{ name: "Garlic shrimp linguine", desc: "Italy meets the sea.", ing: ["100 g linguine", "150 g shrimp", "3 garlic cloves", "Chili", "Parsley, olive oil"], steps: ["Fry shrimp with garlic 3 min.", "Add pasta, toss.", "Parsley on top."] },
{ name: "Zucchini bolognese", desc: "Light but with bite.", ing: ["150 g ground beef", "2 zucchini", "400 g tomatoes", "1 onion", "Parmesan"], steps: ["Cut zucchini into spaghetti, sear.", "Cook bolognese classic-style.", "Serve instead of pasta."] },
{ name: "Cheese spaetzle", desc: "Alpine hut at home.", ing: ["250 g spaetzle", "150 g mountain cheese", "2 onions", "Butter", "Chives"], steps: ["Cook spaetzle.", "Brown onions in butter.", "Layer with cheese, gratinate."] },
{ name: "Cod with potatoes & spinach", desc: "Nordic, clean, good.", ing: ["150 g cod", "300 g potatoes", "200 g spinach", "1 lemon", "Butter"], steps: ["Boil potatoes 20 min.", "Steam fish 8 min.", "Wilt spinach, plate."] },
{ name: "Trout with almonds", desc: "Classic from the tray.", ing: ["1 trout (ready to cook)", "30 g flaked almonds", "300 g potatoes", "Lemon", "Butter"], steps: ["Boil potatoes.", "Fry trout 4 min per side in butter.", "Toast almonds on top."] },
{ name: "Oven salmon honey-mustard", desc: "Glaze meets juiciness.", ing: ["150 g salmon", "1 tbsp honey", "1 tbsp mustard", "300 g broccoli", "80 g rice"], steps: ["Oven 200 °C.", "Glaze salmon, bake 12 min.", "Serve with rice and broccoli."] },
{ name: "Sesame tuna steak", desc: "Glass-like inside, crunch outside.", ing: ["180 g tuna steak", "2 tbsp sesame", "Soy sauce", "1 lime", "Side salad"], steps: ["Coat steak in sesame.", "Sear 1 min per side.", "With soy sauce and lime."] },
{ name: "Fish tacos", desc: "Street food to build yourself.", ing: ["4 tortillas", "200 g pollock", "100 g red cabbage", "Lime", "Yogurt sauce"], steps: ["Bread or season fish, fry.", "Shred cabbage, stir sauce.", "Fill tacos."] },
{ name: "Pollock with pea mash", desc: "Canteen, but good.", ing: ["150 g pollock", "300 g peas (frozen)", "300 g potatoes", "Mint", "Butter"], steps: ["Boil potatoes and peas.", "Mash with mint.", "Fry fish, plate."] },
{ name: "Shrimp coconut curry", desc: "Exotic in 20 minutes.", ing: ["150 g shrimp", "200 ml coconut milk", "2 tbsp red curry paste", "1 bell pepper", "80 g rice"], steps: ["Cook rice.", "Fry paste, add coconut milk.", "Cook shrimp and pepper 5 min."] },
{ name: "Fried fish with potato salad", desc: "Chip-shop feeling.", ing: ["150 g pollock fillet", "Breadcrumbs & egg", "400 g potatoes", "Vinegar, oil, cucumber", "Remoulade"], steps: ["Dress potato salad, rest.", "Bread fish, fry golden.", "Serve with remoulade."] },
{ name: "Chicken breast with oven veg", desc: "Tray in, feet up.", ing: ["150 g chicken breast", "400 g oven veg mix", "2 tbsp olive oil", "Rosemary", "Salt, pepper"], steps: ["Oven 200 °C.", "Roast all 25 min.", "Slice, serve."] },
{ name: "Beef steak with sweet potato", desc: "Sunday, but on Tuesday.", ing: ["180 g beef steak", "1 sweet potato", "100 g beans", "Butter", "Salt, pepper"], steps: ["Bake sweet potato 25 min.", "Sear steak 2–3 min per side, rest.", "Steam beans, plate."] },
{ name: "Turkey strips in mushroom cream", desc: "Cream, mushrooms, done.", ing: ["150 g turkey strips", "200 g mushrooms", "150 ml cream", "1 onion", "80 g rice"], steps: ["Cook rice.", "Sear turkey, add mushrooms.", "Reduce cream, season."] },
{ name: "Meatballs in tomato sauce", desc: "Small, round, happy.", ing: ["200 g ground beef", "400 g tomatoes", "1 egg", "Breadcrumbs", "80 g rice"], steps: ["Mix and form balls.", "Brown them.", "Simmer in tomato sauce 15 min."] },
{ name: "Chicken madras curry", desc: "Fire with coconut.", ing: ["150 g chicken", "200 ml coconut milk", "2 tbsp madras paste", "1 onion", "80 g rice"], steps: ["Cook rice.", "Fry chicken, add paste and milk.", "Simmer 15 min."] },
{ name: "Pork fillet with apple red cabbage", desc: "Feast with no occasion.", ing: ["180 g pork fillet", "300 g red cabbage", "1 apple", "Mustard", "Potato side"], steps: ["Sear fillet, finish 15 min at 160 °C.", "Warm cabbage with apple.", "Slice, serve with mustard."] },
{ name: "Beef goulash", desc: "Patience pays off.", ing: ["200 g beef goulash", "2 onions", "2 tbsp paprika", "500 ml stock", "Potatoes"], steps: ["Brown meat and onions.", "Add paprika, deglaze with stock.", "Braise 60 min."] },
{ name: "Homemade chicken nuggets", desc: "Crispy without the bag.", ing: ["150 g chicken breast", "Breadcrumbs & egg & flour", "Paprika", "Dip of choice", "Salad"], steps: ["Cut chicken, bread it.", "Bake 20 min.", "Serve with dip."] },
{ name: "Turkey burger", desc: "Lighter than beef, just as good.", ing: ["150 g ground turkey", "1 burger bun", "Salad, tomato", "Yogurt-mustard sauce", "Cheese (optional)"], steps: ["Form patty, season, fry.", "Toast bun.", "Stack with sauce."] },
{ name: "Chicken skewers with pepper", desc: "From grill or pan.", ing: ["150 g chicken breast", "1 bell pepper", "1 zucchini", "Marinade: oil, paprika, garlic", "Flatbread"], steps: ["Marinate meat, skewer.", "Grill 12 min all around.", "Serve with bread."] },
{ name: "Cevapcici with flatbread", desc: "Balkan night at home.", ing: ["200 g ground beef", "1 onion", "Ajvar", "Flatbread", "Kajmak or yogurt"], steps: ["Season beef, form rolls.", "Fry all around.", "With bread, ajvar and dip."] },
{ name: "Asian beef strips", desc: "Wok heat in 20 minutes.", ing: ["150 g beef strips", "200 g wok veg", "3 tbsp soy sauce", "Ginger, garlic", "80 g rice"], steps: ["Cook rice.", "Sear beef hot.", "Add veg, deglaze with sauce."] },
{ name: "Chickpea curry", desc: "Creamy, vegan, cheap.", ing: ["240 g chickpeas (can)", "200 ml coconut milk", "2 tbsp curry paste", "200 g spinach", "80 g rice"], steps: ["Cook rice.", "Fry paste, simmer milk and chickpeas 10 min.", "Fold in spinach."] },
{ name: "Lentil bolognese", desc: "Meatless but hearty.", ing: ["100 g red lentils", "100 g pasta", "400 g tomatoes", "1 carrot", "Parmesan (optional)"], steps: ["Cook lentils with tomatoes 20 min.", "Cook pasta.", "Mix, serve."] },
{ name: "Veg coconut curry", desc: "Save leftovers, win flavor.", ing: ["400 g veg of choice", "200 ml coconut milk", "2 tbsp curry paste", "80 g rice", "Lime"], steps: ["Cook rice.", "Cook veg in curry-coconut 12 min.", "Lime over."] },
{ name: "Oven veg with feta", desc: "One tray, zero stress.", ing: ["500 g veg mix", "100 g feta", "2 tbsp olive oil", "Thyme", "Baguette"], steps: ["Roast veg 25 min at 200 °C.", "Add feta last 5 min.", "Serve with baguette."] },
{ name: "Zucchini fritters with dip", desc: "Crispy from the pan.", ing: ["2 zucchini", "1 egg", "3 tbsp flour", "Yogurt dip", "Salt"], steps: ["Grate zucchini, salt, squeeze.", "Mix with egg and flour, fry fritters.", "Serve with dip."] },
{ name: "Cauliflower curry", desc: "Gentle-spicy, very filling.", ing: ["1/2 cauliflower", "200 ml coconut milk", "2 tbsp curry paste", "80 g rice", "Coriander"], steps: ["Cook rice.", "Cook cauliflower in curry-coconut 15 min.", "Coriander on top."] },
{ name: "Ratatouille with baguette", desc: "South of France by the spoon.", ing: ["1 zucchini", "1 eggplant", "1 bell pepper", "400 g tomatoes", "Baguette, herbs"], steps: ["Dice veg, braise in layers.", "Reduce 30 min.", "Serve with baguette."] },
{ name: "Mushroom risotto", desc: "Stirring pays off.", ing: ["80 g risotto rice", "250 g mushrooms", "500 ml stock", "40 g parmesan", "1 shallot, butter"], steps: ["Sweat shallot and rice.", "Add stock bit by bit, stir 20 min.", "Fold in mushrooms and parmesan."] },
{ name: "Pumpkin risotto", desc: "Autumn in a bowl.", ing: ["80 g risotto rice", "300 g hokkaido", "500 ml stock", "40 g parmesan", "Sage"], steps: ["Dice pumpkin, roast.", "Cook like risotto with pumpkin.", "Add parmesan and sage."] },
{ name: "Spinach lentil dal", desc: "Indian soul food.", ing: ["120 g red lentils", "200 g spinach", "400 ml coconut milk", "Curry, cumin", "80 g rice"], steps: ["Cook rice.", "Cook lentils in coconut milk 15 min.", "Add spices and spinach."] },
{ name: "Eggplant parmesan", desc: "Italy, gratinated.", ing: ["1 eggplant", "400 g tomatoes", "100 g mozzarella", "Parmesan", "Basil"], steps: ["Slice eggplant, salt, fry.", "Layer with sauce and cheese.", "Bake 25 min."] },
{ name: "Corn chili sin carne", desc: "Smoky, hearty, vegan.", ing: ["200 g corn", "240 g kidney beans", "400 g tomatoes", "Chili, cumin", "Rice or bread"], steps: ["Everything into one pot.", "Simmer 20 min.", "Serve with rice or bread."] },
{ name: "Chicken caesar salad", desc: "Crunchy with cult dressing.", ing: ["150 g chicken breast", "150 g romaine", "30 g parmesan", "Croutons", "Caesar dressing"], steps: ["Fry chicken, slice.", "Wash salad, mix.", "Dressing, parmesan, croutons."] },
{ name: "Greek village salad", desc: "Holiday in 10 minutes.", ing: ["2 tomatoes", "1/2 cucumber", "1/2 red onion", "100 g feta", "Olives, oregano, oil"], steps: ["Chop all roughly.", "Feta on top, oil and oregano."] },
{ name: "Couscous salad", desc: "Fluffy-fresh, meal-prep ready.", ing: ["80 g couscous", "1 bell pepper", "Cherry tomatoes", "Mint, parsley", "Lemon, oil"], steps: ["Soak couscous in hot water.", "Mix in veg and herbs.", "Dress lemony."] },
{ name: "Quinoa salad with avocado", desc: "Filling with good fats.", ing: ["80 g quinoa", "1 avocado", "100 g cherry tomatoes", "Lime", "Coriander"], steps: ["Cook quinoa, cool.", "Dice all and mix.", "Lime over."] },
{ name: "Mediterranean pasta salad", desc: "BBQ side-dish king.", ing: ["100 g fusilli", "100 g sun-dried tomatoes", "50 g olives", "50 g feta", "Basil, oil"], steps: ["Cook pasta, cool.", "Mix all.", "Let it meld."] },
{ name: "Lentil salad", desc: "Protein from the can.", ing: ["240 g beluga lentils (can/jar)", "1 bell pepper", "1 apple", "Walnuts", "Mustard-honey dressing"], steps: ["Rinse lentils.", "Dice pepper and apple.", "Mix with dressing and nuts."] },
{ name: "Light egg salad", desc: "With yogurt instead of mayo.", ing: ["3 eggs", "150 g yogurt", "1 tbsp mustard", "Chives", "Whole-grain bread"], steps: ["Boil eggs 8 min, dice.", "Mix with yogurt and mustard.", "Chives on top, bread aside."] },
{ name: "Lamb's lettuce with goat cheese", desc: "Nutty, creamy, classy.", ing: ["100 g lamb's lettuce", "80 g goat cheese", "Walnuts", "1 pear", "Honey-mustard dressing"], steps: ["Wash salad.", "Slice pear, crumble cheese.", "Dress, nuts on top."] },
{ name: "Tabbouleh", desc: "Parsley power from Beirut.", ing: ["60 g bulgur", "1 bunch parsley", "2 tomatoes", "Mint", "Lemon, oil"], steps: ["Soak bulgur.", "Finely chop herbs and tomatoes.", "Mix all, season lemony."] },
{ name: "Swabian potato salad", desc: "No mayo, with stock.", ing: ["500 g potatoes", "1 onion", "150 ml stock", "Vinegar, oil, mustard", "Chives"], steps: ["Boil potatoes, peel, slice.", "Pour hot stock marinade over.", "Rest, add chives."] },
{ name: "Pumpkin soup", desc: "Velvety-orange autumn love.", ing: ["500 g hokkaido", "1 onion", "500 ml stock", "100 ml cream", "Ginger, curry"], steps: ["Sweat pumpkin and onion.", "Cook in stock 15 min.", "Blend, add cream."] },
{ name: "Tomato soup with basil", desc: "Simple, honest, good.", ing: ["800 g canned tomatoes", "1 onion", "500 ml stock", "Basil", "Cream swirl"], steps: ["Sweat onion, simmer tomatoes 15 min.", "Blend.", "Basil and cream on top."] },
{ name: "Classic chicken soup", desc: "Grandma's medicine.", ing: ["200 g chicken breast", "2 carrots", "1 leek", "100 g soup noodles", "1 l stock"], steps: ["Cook chicken in stock 20 min.", "Add veg, simmer 15 min.", "Add noodles, shred meat."] },
{ name: "Minestrone", desc: "Italian veg pot.", ing: ["300 g veg mix", "100 g white beans (can)", "50 g small pasta", "700 ml stock", "Parmesan"], steps: ["Sweat veg.", "Add stock, simmer 20 min.", "Cook beans and pasta in it."] },
{ name: "Potato soup", desc: "Hearty-creamy by the spoon.", ing: ["500 g potatoes", "1 leek", "700 ml stock", "100 ml cream", "Marjoram, sausage (optional)"], steps: ["Cook all 20 min.", "Blend, add cream.", "Season with marjoram."] },
{ name: "Broccoli cream soup", desc: "Green, velvety, fast.", ing: ["500 g broccoli", "1 potato", "500 ml stock", "100 ml cream", "Nutmeg"], steps: ["Cook all 15 min.", "Blend.", "Add cream and nutmeg."] },
{ name: "Light pho with chicken", desc: "Vietnam's soul warmer.", ing: ["100 g rice noodles", "150 g chicken breast", "1 l stock", "Ginger, star anise", "Limes, herbs, soy sauce"], steps: ["Simmer stock with spices 15 min.", "Poach chicken, slice.", "Pour over noodles, assemble."] },
{ name: "Pea soup", desc: "Hearty works without bacon too.", ing: ["400 g split peas", "2 carrots", "1 onion", "1 l stock", "Marjoram"], steps: ["Soak peas 1 hr (or frozen).", "Simmer all 30 min.", "Blend partly, season."] },
{ name: "Hummus with veg sticks", desc: "Dipping allowed.", ing: ["240 g chickpeas (can)", "2 tbsp tahini", "1 lemon", "Garlic, cumin", "Veg sticks"], steps: ["Blend all but sticks creamy.", "Drizzle oil.", "Sticks aside."] },
{ name: "Guacamole with tortilla chips", desc: "Mexico in 10 minutes.", ing: ["2 avocados", "1 tomato", "1 lime", "Coriander, chili", "Tortilla chips"], steps: ["Mash avocados.", "Stir in tomato, lime, spices.", "Serve with chips."] },
{ name: "Date-cocoa protein balls", desc: "Energy balls, no baking.", ing: ["150 g dates", "100 g oats", "2 tbsp cocoa", "2 tbsp peanut butter", "Coconut flakes"], steps: ["Blend all.", "Form balls.", "Roll in coconut, chill."] },
{ name: "Roasted chickpeas", desc: "Chips alternative from the oven.", ing: ["240 g chickpeas (can)", "1 tbsp olive oil", "Paprika", "Salt"], steps: ["Dry, mix with oil and spices.", "Roast 25 min at 200 °C."] },
{ name: "Oven nachos", desc: "Movie-night upgrade.", ing: ["150 g tortilla chips", "100 g cheese", "100 g beans", "Jalapeños", "Salsa, yogurt"], steps: ["Layer chips, top.", "Gratinate 10 min.", "Salsa and yogurt aside."] },
{ name: "Bruschetta", desc: "Summer on bread.", ing: ["4 slices ciabatta", "3 tomatoes", "1 garlic clove", "Basil", "Olive oil"], steps: ["Toast bread, rub with garlic.", "Dice tomatoes, season.", "Top, drizzle oil."] },
{ name: "Tzatziki with flatbread", desc: "Greece for dipping.", ing: ["250 g yogurt", "1/2 cucumber", "1 garlic clove", "Dill", "Flatbread, olive oil"], steps: ["Grate cucumber, squeeze.", "Mix with yogurt and garlic.", "Oil over, bread aside."] },
{ name: "Edamame with sea salt", desc: "Sushi-bar snack at home.", ing: ["300 g edamame (frozen)", "Sea salt", "Chili flakes (optional)"], steps: ["Boil or steam 5 min.", "Salt, snack warm."] },
{ name: "Homemade trail mix", desc: "Trail mix without sugar trap.", ing: ["50 g almonds", "50 g walnuts", "30 g dark choc chips", "30 g raisins"], steps: ["Mix all.", "Portion."] },
{ name: "Apple slices with almond butter", desc: "Crunchy-creamy snack.", ing: ["1 apple", "2 tbsp almond butter", "Cinnamon"], steps: ["Cut apple into wedges.", "Butter aside, cinnamon over."] },
{ name: "Rice cakes with cottage cheese", desc: "Light and fast.", ing: ["2 rice cakes", "100 g cottage cheese", "Cress or tomato", "Salt, pepper"], steps: ["Spread cakes.", "Top, season."] },
{ name: "Banana protein shake", desc: "Post-workout in 5 minutes.", ing: ["1 banana", "250 ml milk", "1 scoop protein powder", "Ice cubes"], steps: ["Blend all.", "Drink ice-cold."] },
{ name: "Falafel wrap", desc: "Street food to roll up.", ing: ["1 tortilla", "5 falafel", "Salad, tomato", "2 tbsp hummus", "Yogurt sauce"], steps: ["Warm falafel.", "Spread tortilla and fill.", "Roll tight."] },
{ name: "Halloumi burger", desc: "Squeakily good.", ing: ["1 burger bun", "120 g halloumi", "Salad, tomato", "Honey-mustard sauce", "Red onion"], steps: ["Fry halloumi golden.", "Toast bun.", "Stack with sauce."] },
{ name: "Chicken club sandwich", desc: "Three stories of happy.", ing: ["3 slices toast", "100 g chicken breast", "2 slices cheese", "Salad, tomato", "Mayo/mustard"], steps: ["Fry chicken, toast toast.", "Layer, cut diagonal.", "Skewer in."] },
{ name: "Tuna sandwich", desc: "Lunchbox upgrade.", ing: ["2 slices whole-grain bread", "1 can tuna", "1 tbsp yogurt", "Cucumber, salad", "Lemon"], steps: ["Mix tuna with yogurt and lemon.", "Fill bread.", "Fold."] },
{ name: "Lentil burger", desc: "Patty from the can.", ing: ["240 g lentils (can)", "1 burger bun", "Oats for binding", "Salad, tomato", "BBQ sauce"], steps: ["Mash lentils, form patties.", "Fry or bake.", "Stack."] },
{ name: "Homemade chicken döner", desc: "Better than the shop.", ing: ["150 g chicken", "1 flatbread", "Salad, tomato, cucumber", "Yogurt-garlic sauce", "Döner spice"], steps: ["Spice chicken, fry, slice.", "Warm bread, cut open.", "Fill, sauce on top."] },
{ name: "Cheese-bean quesadilla", desc: "Crispy, cheesy, fast.", ing: ["2 tortillas", "100 g cheese", "100 g black beans", "Corn", "Salsa"], steps: ["Top one tortilla.", "Second on top, fry crispy both sides.", "Cut into triangles."] },
{ name: "Caprese panini", desc: "Toast with an Italian soul.", ing: ["1 ciabatta roll", "125 g mozzarella", "2 tomatoes", "Basil", "Pesto"], steps: ["Spread roll with pesto.", "Fill.", "Toast until cheese runs."] },
{ name: "Salmon bagel", desc: "Brunch classic.", ing: ["1 bagel", "100 g smoked salmon", "Cream cheese", "Arugula", "Lemon, dill"], steps: ["Toast bagel, spread.", "Salmon and arugula on top.", "Lemon and dill."] },
{ name: "Egg sandwich with cress", desc: "Simple, fast, good.", ing: ["2 slices toast", "2 eggs", "Cress", "1 tbsp yogurt", "Salt, pepper"], steps: ["Boil eggs, dice.", "Mix with yogurt.", "Top, add cress."] },
{ name: "Quark bake with berries", desc: "Cake that does protein.", ing: ["500 g low-fat quark", "2 eggs", "50 g semolina", "200 g berries", "Vanilla, sweetener"], steps: ["Stir all.", "Bake 30 min at 180 °C.", "Serve warm or cold."] },
{ name: "Protein rice pudding", desc: "Soul food with purpose.", ing: ["80 g pudding rice", "500 ml milk", "1 scoop vanilla protein", "Cinnamon", "Cherries (optional)"], steps: ["Cook rice pudding 20 min.", "Stir in protein.", "Cinnamon on top."] },
{ name: "Baked apples with quark", desc: "Winter dessert, light.", ing: ["2 apples", "200 g low-fat quark", "Cinnamon", "1 tsp honey", "Walnuts"], steps: ["Core apples, bake 20 min.", "Stir quark with cinnamon and honey.", "Fill, nuts on top."] },
{ name: "Chocolate protein mousse", desc: "Dessert without regret.", ing: ["250 g low-fat quark", "1 tbsp cocoa", "1 scoop chocolate protein", "100 ml milk", "Berries"], steps: ["Blend all creamy.", "Chill.", "Berries on top."] },
{ name: "Light semolina flummery", desc: "Wobble pudding for grown-ups.", ing: ["40 g semolina", "400 ml milk", "1 egg white", "Vanilla", "Fruit sauce"], steps: ["Cook semolina pudding, cool.", "Fold in beaten white.", "Chill, sauce aside."] },
{ name: "Berry yogurt ice", desc: "Nice cream, no machine.", ing: ["200 g frozen berries", "150 g yogurt", "1 tbsp honey"], steps: ["Blend all creamy.", "Spoon now or freeze."] },
{ name: "Green smoothie", desc: "Vitamin boost in a glass.", ing: ["1 handful spinach", "1/2 mango", "1 banana", "200 ml water", "Lime"], steps: ["Blend all.", "Drink ice-cold."] },
{ name: "Mango lassi", desc: "Indian-creamy, light.", ing: ["1 mango", "200 g yogurt", "100 ml milk", "Cardamom", "Ice"], steps: ["Blend all.", "Dust with cardamom."] },
{ name: "Warm cocoa protein", desc: "Evening chocolate dream with purpose.", ing: ["250 ml milk", "1 tbsp cocoa", "1 scoop chocolate protein"], steps: ["Warm milk.", "Stir in cocoa and protein."] } ] };
